### ISSUE TITLE
Questions about train_ratio and optimization procedure

### ISSUE THREAD

**Issue by zzzc18** [danijar/dreamerv3#13]
I noticed that `driver.on_step(train_step)` registers `train_step`  as a callback function triggered each time the agent interacts with the real environment. If i understood correctly then after collecting a frame from the real environment, the agent will do these things for train_ratio times(say 64 in the example):
- Sample 16*64 obs,action,etc. from the replay buffer
- Train the WorldModel with these data, and use the 16*64 obs,action as starting info for imagination
- Train the Actor-Critic model by imagining(start from the context info)

My questions is:
- Is it necessary to train the world model repeatedly with the same data? As far as I know this may result in converging to a local optimum.

The code is quite complicated, and I'm not sure if there are any mechanism leds to different results than my description above.

**Comment by zzzc18** [comment]
I print the shape of `start` of `self.task_behavior.train(self.wm.imagine, start, context)` and find out it comes from reshaping:`BatchSize BatchLength Dim -> BatchSize*BatchLength Dim`, so this may not be correct:
> - Train the WorldModel with these data, and collect the context info calculated by the world model

Still I think there exists  non-stationary issue.

**Comment by danijar** [comment]
Hi, the steps you describe are correct. But it would never use the same batch multiple times. Each gradient step is computed from a different batch randomly sampled from the replay buffer.

By the way, the train_ratio is the ratio of replayed frames to env frames. Because a replay batch contains 16*64=1024 steps, it's not 64 replay batches per env step but rather 64/1024=1/16 replay batch per env step i.e. one batch every 16 env steps.

**Comment by zzzc18** [comment]
@danijar Thanks for replying. Perhaps you may use symbols to describe `train_ratio` in your paper, as `env frames` and `env steps` can be easily confused.
