### ISSUE TITLE
About rep_loss

### ISSUE THREAD

**Issue by andyshuo** [danijar/dreamerv3#159]
I understand that dyn_loss is to backward the GRU cell.
However, why do we need to prior || sg(post) (KL divergence).
what does rep_loss. 
I suppose the representation learning is well trained by the decoder (VAE mechanism).

Would you please tell me why do we need the rep_loss?

**Comment by danijar** [comment]
It's a regularizer for the representation, just like the KL regularizer in a VAE. It helps keep the codes stochastic, so that the GRU gets to see all kinds of different codes during training and thus is less surprised by unexpected inputs at inference time (e.g. when self-generated inputs are looped back in).
