### ISSUE TITLE
Replay Sequences

### ISSUE THREAD

**Issue by NonsansWD** [danijar/dreamerv3#162]
Hello,
After training there is a replay folder saved with npz files and each of those seem to be for 1 epoch of 800 timesteps. From what I saw in those files, there are no frames saved but I need the frames corresponding to the rest of that dictionaries data. The way i tried to solve this is by making an environment for the task I want to check and then calling env.step(action) for every single action in one npz file and at the same time saving all those returned observations and making a little video from that but unfortunately that resulted in a video with the trained agent completely failing the task even tho the summed up reward for that npz file is around 1000. Is there anything I could do to fix this or get the frames in another way? Any help would be really much appreciated

**Comment by danijar** [comment]
To get a video, you can add a `log_image` observation to your environment. That will give a video to the logger, without allowing the agent to train on it (because of the `log_` prefix). The NPZ are chunks of the replay buffer that contain a fixed number of time steps, with episode boundaries anywhere in between.
