### ISSUE TITLE
How to use batch env

### ISSUE THREAD

**Issue by RuiHirano** [danijar/dreamerv3#44]
Hello.
Thank you for providing us with a great algorithm.
I have a question about batch env.
I have specified two envs in batchenv because of the slow progress of the game agent I am currently training.
However, when I checked the progress in sensorboard, there was no change and it was not doubled in speed.
Is it correct to use batchenv? Also, what does the parallel parameter represent?

Thank you in advance.

**Comment by danijar** [comment]
Hi, if you use train.py (as opposed to the simplified example.py) then you already get parallel training for free. Doubling the number of environments might not speed up things that much though, because it only speeds up data collection (up to your available CPU resources and constant overhead of copying observations/actions to/from the GPU for the policy forward pass). Often, the bottleneck is training not data collection. You can speed that up by training with multiple GPUs.
